---
name: HTML Lints

on:
  push:
    tags:
      - 'latest'
      - 'v*'
  pull_request:
    branches:
    - 'master'
  workflow_dispatch:

env:
  CI_IMAGE_NAME: 'ghcr.io/cradle8810/htmllint'      

jobs:
    docker-image-build:
        runs-on: ubuntu-latest
        steps:

        - name: Checkout
          uses: actions/checkout@v4

        - name: Kick Buildx
          uses: docker/setup-buildx-action@v3
        
        - name: Docker meta
          id: docker_meta
          uses: docker/metadata-action@v5
          with:
            images: ${{ env.CI_IMAGE_NAME }}
            labels: |
              org.opencontainers.image.source = "https://github.com/cradle8810/htmllint-cli"

        - name: Login to DockerHub
          uses: docker/login-action@v3
          with:
            registry: ghcr.io
            username: true
            password: ${{ secrets.CR_PAT }}

        - name: docker build and push
          uses: docker/build-push-action@v2
          with:
            context: .
            push: ${{ github.event_name != 'pull_request' }}
            tags: ${{ steps.docker_meta.outputs.tags }}
            labels: ${{ steps.docker_meta.outputs.labels }}
